@startuml

class InventoryTrackerController
{
currentSerialNumber : String
addItemButtonClicked()
deleteButtonClicked()
editStart()
editCommit()
searchBarTyped()
saveButtonClicked()
openButtonClicked()
warningDialogHandler()
addItem()
deleteItem()
editItem()
save()
open()
getItemObservableList()
updateTableView()
clearTextFields()
}

class InventoryList
{
itemList : TreeMap
addItem()
deleteItem()
editItem()
getItemList()
getItemObservableList()
getSearchResults()
}

class Item
{
serialNumber : String
itemName : String
price : String
getSerialNumber()
getItemName()
getPrice()
setSerialNumber()
setItemName()
setPrice()
}

class FileManager
{
selectedFile : File
getJSONString()
getHTMLString()
getTSVString()
save()
getFileInput()
getItemList()
}

class Validator
{
validateItemName()
validateSerialNumber()
validatePrice()
}

InventoryTrackerController -- InventoryList
InventoryList -- Item
InventoryTrackerController -- FileManager

@enduml